import { Inter, Poppins } from "next/font/google";
import Header from "@/components/navbar/Header";
import "../globals.css";
import { dir } from "i18next";
import initTranslations from "../i18n";
import i18nConfig from "../../../i18nConfig";
import Footer from "@/components/footer/Footer";
import TranslationsProvider from "../../components/TranslationsProvider/TranslationsProvider";


const poppins = Poppins({
	weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
	subsets: ["latin"],
});

export function generateStaticParams() {
	return i18nConfig.locales.map((locale) => ( locale ));
}

export const metadata = {
	title: "Dr Khaled ",
	description: "Generated by create next app",
};

const i18nNamespaces = ["home"];

export default async function RootLayout({ children, params }) {
	const {locale}=params
	const { resources, t } = await initTranslations(locale, i18nNamespaces);

	return (
		<html lang={locale} dir={dir(locale)}>

			<body className={poppins.className}>
				<TranslationsProvider
					namespaces={i18nNamespaces}
					locale={locale}
					resources={resources}
				>
					<Header params={params} />
					{children}
					<Footer params={params}/>
				</TranslationsProvider>
			</body>
		</html>
	);
}
